version: '3'
services:
  web:
    container_name: 'private-isu_web'
    build: .
    command: "bundle exec rackup -p 8080 -o 0.0.0.0"
    volumes:
      - ./:/app
    ports:
      - 8080:8080
    depends_on:
      - db
      - memcached
    tty: true
    stdin_open: true
    environment:
      ISUCONP_DB_HOST: db
      ISUCONP_MEMCACHED_HOST: memcached
  nginx:
    image: nginx
    ports:
      - 8888:80
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./public:/var/www/public
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
  db:
    image: mysql:5.6
    environment:
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    ports:
      - 3306:3306
    volumes:
    - mysql-volume:/var/lib/mysql
    - ./db:/var/tmp
  memcached:
    image: memcached:1.4
    ports:
      - 11211:11211
volumes:
  mysql-volume:
